<?PHP

/**
 * Google+ (plus.google.com) PHP Curl bot
 * @since Sep 29 2011
 * @version 05.08.2012
 * @link http://360percents.com/
 * @author Luka Pušić <luka@pusic.si>
 * @author Florian Knodt <adlerweb@adlerweb.info>
 */
class gplusBot{
    /**
     * @var string File to store cookies during transaction
     */
    private $cookies;
    
    /**
     * @var int Number of seconds to wait between requests
     */
    private $sleep;
    
    /**
     * @var string User Agent sent to google
     */
    private $uagent;
    
    /**
     * @var bool|int false = off, 1 = basic, 2 = full debug
     */
    private $debug;
    
    /**
     * Constructor - connect to G+ and log in
     *
     * @param string E-Mail adress
     * @param string Password
     * @param string Filename for temporary cookie storage
     * @param bool|int Number of seconds to wait between requests, false = random
     * @param bool|string User agent sent to google
     * @param bool|int Debug-Mode: false = off, 1 = basic, 2 = full debug
     */
    function __construct($user, $pass, $cookies='cookie.txt', $sleep=false, $uagent=false, $debug=2) {
        //Defaults
        $this->sleep    = ($sleep === false)    ? rand(3,15) : $sleep;
        $this->uagent   = ($uagent === false)   ? 'Mozilla/4.0 (compatible; MSIE 5.0; S60/3.0 NokiaN73-1/2.0(2.0617.0.0.7) Profile/MIDP-2.0 Configuration/CLDC-1.1)' : $uagent;
        $this->cookies  = $cookies;
        $this->debug    = $debug;
        
        //Clean cookies
        if(file_exists($this->cookies)) unlink($this->cookies);
        touch($this->cookies);
        
        //Login
        $data=($this->login_data($user, $pass));
        $this->login($data);
    }
    
    /**
     * Destructor - logout and clean up
     */
    function __destruct() {
        $this->logout();
        if(file_exists($this->cookies)) unlink($this->cookies);
    }
    
    /**
     * Login_data - Collect login informatioin
     * @param string E-Mail
     * @param string Password
     * @return array Data needed to log in
     */
    function login_data($user, $pass) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_COOKIEJAR, $this->cookies);
        curl_setopt($ch, CURLOPT_COOKIEFILE, $this->cookies);
        curl_setopt($ch, CURLOPT_USERAGENT, $this->uagent);
        curl_setopt($ch, CURLOPT_URL, "https://plus.google.com/");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    
        $buf = utf8_decode(html_entity_decode(curl_exec($ch)));
        sleep($this->sleep);
        $buf = str_replace( '&amp;', '&', $buf ); // just in case any correctly encoded
        $buf = str_replace( '&', '&amp;', $buf ); // now encode them all again
        curl_close($ch);
    
        $this->debug('[+] Sending GET request to: https://plus.google.com/', 1);
        $this->debug($buf, 2);
    
        $toreturn = array();
    
        $doc = new DOMDocument;
        $doc->loadhtml($buf);
        $inputs = $doc->getElementsByTagName('input');
        foreach ($inputs as $input) {
            switch ($input->getAttribute('name')) {
                case 'Email':
                    $toreturn[] = 'Email='.urlencode($user);
                    break;
                case 'Passwd':
                    $toreturn[] = 'Passwd=' . urlencode($pass);
                    break;
                default:
                    $toreturn[] = $input->getAttribute('name').'='.urlencode($input->getAttribute('value'));
            }
        }
        
        sleep($this->sleep);
        return array(implode('&', $toreturn), $doc->getElementsByTagName('form')->item(0)->getAttribute('action'));
    }
    
    /**
     * Send login information to google
     * @param array Login information generated by login_data()
     * @see login_data
     */
    function login($postdata) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_COOKIEJAR, $this->cookies);
        curl_setopt($ch, CURLOPT_COOKIEFILE, $this->cookies);
        curl_setopt($ch, CURLOPT_USERAGENT, $this->uagent);
        curl_setopt($ch, CURLOPT_URL, $postdata[1]);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata[0]);
        $buf = curl_exec($ch); #this is not the g+ home page, because the b**** doesn't redirect properly
        sleep($this->sleep);
        curl_close($ch);
        $this->debug($buf, 2);
    
        $this->debug('[+] Sending POST request to: '.$postdata[1], 1);
    }
    
    /**
     * Post something to our profile
     * @param string Message to post
     */
    function update_profile_status($status) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_COOKIEJAR, $this->cookies);
        curl_setopt($ch, CURLOPT_COOKIEFILE, $this->cookies);
        curl_setopt($ch, CURLOPT_USERAGENT, $this->uagent);
        curl_setopt($ch, CURLOPT_URL, 'https://m.google.com/app/plus/?v=compose&group=m1c&hideloc=1');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        $buf = utf8_decode(html_entity_decode(str_replace('&', '', curl_exec($ch))));
        sleep($this->sleep);
        $header = curl_getinfo($ch);
        curl_close($ch);
        $this->debug($buf, 2);
    
        $params = array();
        $doc = new DOMDocument;
        $doc->loadhtml($buf);
        $this->debug($buf, 2);
        $inputs = $doc->getElementsByTagName('input');
        foreach ($inputs as $input) {
            if (($input->getAttribute('name') != 'editcircles')) {
                $params[] = $input->getAttribute('name') . '=' . urlencode($input->getAttribute('value'));
            }
        }
        $params[] = 'newcontent=' . urlencode($status);
        $baseurl = 'https://m.google.com' . parse_url($header['url'], PHP_URL_PATH);
    
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_COOKIEJAR, $this->cookies);
        curl_setopt($ch, CURLOPT_COOKIEFILE, $this->cookies);
        curl_setopt($ch, CURLOPT_USERAGENT, $this->uagent);
        //delete group=b0& in the line below, to post just to your circles, not to public
        curl_setopt($ch, CURLOPT_URL, $baseurl . '?v=compose&group=m1c&group=b0&hideloc=1&a=post');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_REFERER, $baseurl . '?v=compose&group=m1c&group=b0&hideloc=1');
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, implode('&', $params));
        $buf = curl_exec($ch);
        sleep($this->sleep);
        $header = curl_getinfo($ch);
        curl_close($ch);
        $this->debug($buf, 2);
    
        $this->debug('[+] POST Updating status on: '.$baseurl, 1);
    }
    
    /**
     * Post something to a definded page - not implemented yes
     */
    function update_page_status() {
        return false; //Not implemented yet
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_COOKIEJAR, $this->cookies);
        curl_setopt($ch, CURLOPT_COOKIEFILE, $this->cookies);
        curl_setopt($ch, CURLOPT_USERAGENT, $this->uagent);
        curl_setopt($ch, CURLOPT_URL, 'https://plus.google.com/u/0/b/' . $GLOBALS['pageid'] . '/');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        $buf = utf8_decode(html_entity_decode(str_replace('&', '', curl_exec($ch))));
        sleep($this->sleep);
        curl_close($ch);
        $this->debug($buf, 2);
    }
    
    /**
     * Terminate current session
     */
    function logout() {
        $this->debug('[+] GET Logging out', 1);
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_COOKIEJAR, $this->cookies);
        curl_setopt($ch, CURLOPT_COOKIEFILE, $this->cookies);
        curl_setopt($ch, CURLOPT_USERAGENT, $this->uagent);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_URL, 'https://www.google.com/m/logout');
        $buf = curl_exec($ch);
        sleep($this->sleep);
        curl_close($ch);
        $this->debug($buf, 2);
    }
    
    /**
     * Debug handler
     * @param string Debug-Message
     * @param int Minimal level for this message
     */
    function debug($message, $level) {
        if(!$this->debug) return;
        if($this->debug >= $level) echo $message."\n";
    }
}

?>

